version: '3'

services:
  hackingtool:
    image: vgpastor/hackingtool
    container_name: hackingtool
    stdin_open: true
    tty: true
    volumes:
      - .:/root/hackingtool
    ports:
      - 22:22
  security-toolkit:
    image: tiameows/security-toolkit
    container_name: security-toolkit
    volumes:
      - .:/root/security-toolkit
    environment:
      - TZ=UTC
    restart: unless-stopped
    privileged: true
    network_mode: host